// Generated by CoffeeScript 1.6.1
(function() {
  var controller;

  controller = typeof exports !== "undefined" && exports !== null ? exports : this;

  controller.FeedListCtrl = function($scope) {
    $scope.feedURL = '';
    $scope.listData = [
      {
        url: "http://feeds.bbci.co.uk/news/rss.xml"
      }, {
        url: "http://www.theverge.com/rss/index.xml"
      }
    ];
    $scope.addFeed = function() {
      $scope.listData.push({
        url: $scope.feedURL
      });
      return $scope.feedURL = '';
    };
    return {
      scope: $scope
    };
  };

}).call(this);
